# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e3993573f5cbf4b81136ee5d8baa7cd34545de9de6937ec282c6fd87e7a17f66b321b55baf62cdc7c5504490f26fae00a62574aee5f6b99ab52db20a47ce23d

test:
  secret_key_base: 74123fbd95a05087c14b1af2258d50d126f4ea9add5102fbe0e3d593264f1624bf3a6469775c5c6dda8db4c090fddd6f49eabbc352328b1d16e58793540efbec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
